In [1]:
import numpy as np
import sys

In [24]:
a = np.array([[1 ,3 ,5, 7, 9], [2, 4, 6, 8, 10]])
a

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [25]:
sys.getsizeof(a)

160

In [26]:
a.shape

(2, 5)

In [27]:
a.ndim

2

In [28]:
a.dtype

dtype('int32')

In [29]:
a.nbytes

40

In [30]:
a.size

10

In [31]:
a.itemsize

4

In [32]:
a[1]

array([ 2,  4,  6,  8, 10])

In [33]:
a[1, 1]

4

In [34]:
a[0, 2]

5

In [35]:
a[0 : ]

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [36]:
a[2 : ]

array([], shape=(0, 5), dtype=int32)

In [37]:
a[1 : ]

array([[ 2,  4,  6,  8, 10]])

In [46]:
a[1, 1 : -1 : 2]

array([4, 8])

In [50]:
a[0, 1]

3

In [60]:
x = np.zeros((3 , 4))

In [61]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
y = np.ones((5, 3, 4))

In [63]:
y

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [68]:
xy= np.full((2, 4), 5)
xy

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [69]:
a

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [70]:
np.full_like(xy, 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [71]:
np.random.rand()

0.5993093012143517

In [74]:
np.random.rand(4, 2)

array([[0.41522351, 0.46286131],
       [0.52920708, 0.15506535],
       [0.53084354, 0.87341278],
       [0.43463888, 0.99658016]])

In [75]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
np.repeat(a, 2, axis = 0)

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])

In [81]:
#shallow Copies

a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [83]:
# deep copies
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


In [86]:
a = np.ones((3,4))
print(a)

b = np.full((3,4), 9)
print(b)

np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)