## NumPy (Numerical Python)

    NumPy stands for Numerical Python. 
    It is a fundamental/ core library needed for scientific computing with Python, which adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

## Remember to Install Numpy 
pip install numpy


    In the first cell we put the code to import the numpy library as np. 
    This is for convenience; every time we need to use some functionality from the numpy library, we will write np instead of numpy.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

### The Basics

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:
# To check the size of an array
# For dtype=int32 = 96 + n * 4 Bytes => a = [1,2,3] => 96 + 3 * 4 = 108 
# For dtype=int64 = 96 + n * 8 Bytes => a = [1,2,3] => 96 + 3 * 8 = 120
# Whereas, 96 Bytes are allocated for other information of the array object (shape, dimension etc.).

import sys
sys.getsizeof(a)

116

In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get Dimension
b.ndim

2

In [24]:
z = np.array([[[1,2], [1,2], [1,2], [1,2]], [[1,2], [1,2], [1,2], [1,2]]])

In [25]:
z.shape

(2, 4, 2)

In [7]:
# Get Shape
b.shape

(2, 3)

In [31]:
a = np.array(
                [   [  [ [1,1], [2,2] ],  [ [3,3], [4,4]| ]  ],
    
                    [  [ [5,5], [6,6] ],  [ [7,7], [8,8] ]  ]   ])


SyntaxError: invalid syntax (<ipython-input-31-2b4d3bc77910>, line 2)

In [32]:
print("Dimensions: ", a.ndim)
print("Shape     : ", a.shape)

Dimensions:  4
Shape     :  (2, 2, 2, 2)


In [33]:
# Get Type
a.dtype

dtype('int32')

In [34]:
# Get Size (Size of one value i.e. size of one value of dtype='int64' = 8)
a.itemsize

4

In [35]:
# Get total size
a.nbytes

64

In [30]:
# Get number of elements
a.size

16

In [62]:
c = np.array([[[1,2], [1,2], [1,2], [1,2]], [[1,2], [1,2], [1,2], [1,2]]])

In [63]:
print('shape = ', c.shape)
print('itemsize = ', c.itemsize)
print('total bytes = ', c.nbytes)
print('size = ', c.size)
print('datatype = ', c.dtype)
print('getsizeof =', sys.getsizeof(a))


shape =  (2, 4, 2)
itemsize =  4
total bytes =  64
size =  16
datatype =  int32
getsizeof = 216


### Accessing/ Changing specific elements

In [78]:
a = np.array([[1, 2, 3,  4,  5,  6,  7],
              [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [79]:
# Get a specific element
a[1, 1]

9

In [80]:
# Get a specific row/ First value of first dimension and all values of second dimension
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [81]:
# Get a specific column/ All values of first dimension and third value of second dimension
a[:, 2]

array([ 3, 10])

In [82]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [90]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [94]:
a[1,5] = 20

a[:,2] = [1,2]

print(a[:,2].shape)
a[:,2]

(2,)


array([1, 2])

3-dim example

In [98]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [99]:
# Get specific element
b[0,1,1]

4

In [100]:
# Replace 
b[:,1,:] = [[9,9],[8,8]]

In [101]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [102]:
# All 0s matrix
z_mat = np.zeros((2,3))
z_mat

array([[0., 0., 0.],
       [0., 0., 0.]])

In [103]:
# All 1's Tensor
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [112]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [113]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [114]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [115]:
# Random decimal number
np.random.rand()

0.81604400673963

In [125]:
# Random decimal numbers array
np.random.rand(4,2)

array([[0.14593356, 0.95281418],
       [0.9548376 , 0.23732626],
       [0.68018545, 0.76472493],
       [0.89523229, 0.84330327]])

In [126]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2, -2,  4],
       [ 4,  7,  0],
       [-3,  6,  6]])

In [127]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [129]:
# Repeat an array
arr = np.array([[5,2,7,7]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

## In numpy axis = 1 by default. 
## axis = 0 along the rows,
## axis = 1 along the columns. 

[[5 2 7 7]
 [5 2 7 7]
 [5 2 7 7]]


In [130]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [131]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [132]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## Mathematics Functions

### Element-wise operations

In [133]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [173]:
a + 2

array([[3., 3., 3.],
       [3., 3., 3.]])

In [174]:
a - 2

array([[-1., -1., -1.],
       [-1., -1., -1.]])

In [175]:
a * 2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [176]:
a / 2

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [177]:
a * a # Element wise multiplication

array([[1., 1., 1.],
       [1., 1., 1.]])

In [178]:
b = np.array([1,0,1,0])
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [179]:
a ** 2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [180]:
# Take the sin
degrees = 360
radians = (degrees * np.pi)/180
print(radians)
np.cos(radians) # Basically the method is used for radian, that's why we need to convert degree to radians first.


6.283185307179586


1.0

In [181]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [182]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [183]:
# Find the determinant
c = np.identity(3)
print(c)
det_v = np.linalg.det(c)
print(det_v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


In [184]:
# Find Trace (Return the sum along diagonals of the array.)
print(np.trace(c))


3.0


In [185]:
e_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
e_mat.shape

(3, 3)

In [186]:
# Eigenvalues 
np.linalg.eigvals(e_mat)

array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16])

In [187]:
ab = np.array([[1,1,3],[1,2,1],[1,1,2]])

# Inverse
np.linalg.inv(ab)

array([[-3., -1.,  5.],
       [ 1.,  1., -2.],
       [ 1., -0., -1.]])

##### Statistics

In [188]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [189]:
np.min(stats)

1

In [190]:
np.max(stats, axis=1)

array([3, 6])

In [191]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [192]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print("Shape: ", before.shape)

print("_______________\n")

after = before.reshape((4,2))
print(after)
print("Shape: ", after.shape)

[[1 2 3 4]
 [5 6 7 8]]
Shape:  (2, 4)
_______________

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape:  (4, 2)


In [193]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [194]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [195]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [199]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [200]:
filedata[~((filedata > 50) & (filedata < 100))]

array([  1,  13,  21,  11, 196,   4,   3,  34,   6,   7,   8,   0,   1,
         2,   3,   4,   5,   3,  42,  12,  33, 766,   4,   6,   4,   3,
         4,   5,   6,   7,   0,  11,  12,   1,  22,  33,  11, 999,  11,
         2,   1,   0,   1,   2,   9,   8,   7,   1])

In [198]:
# Python way to make copy from list/dictionaly/tuple etc
# mlist = [x for x in filedata]
# mlist